/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.gui;

import carrentalsystem.model.Car;
import carrentalsystem.model.Customer;
import carrentalsystem.model.Rental;
import carrentalsystem.util.FileManager;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author alianaam
 */
public class BookForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookForm.class.getName());
    private final DataManager dm = DataManager.getInstance();
    private DefaultTableModel tableModel;


    /**
     * Creates new form BookForm
     */
    public BookForm() {
        initComponents();
        setupTable();
        refreshAvailableCars();
        loadCustomersToCombo();
        getContentPane().setBackground(new java.awt.Color(240, 248, 255)); // light blue background
        setTitle("Car Rental System");
    }
    
    private void setupTable() {
        tableModel = new DefaultTableModel(
            new String[]{"Car ID", "Brand", "Model", "Plate Number", "Daily Rate"}, 0);
        tblAvailableCars.setModel(tableModel);
    }

    private void refreshAvailableCars() {
        tableModel.setRowCount(0);
        for (Car c : dm.getCars()) {
            if ("Available".equals(c.getStatus())) {
                tableModel.addRow(new Object[]{
                    c.getId(), c.getBrand(), c.getModel(), 
                    c.getPlateNumber(), c.getDailyRate()
                });
            }
        }
    }
    private void loadCustomersToCombo() {
        cmbCustomer.removeAllItems();
        for (Customer c : dm.getCustomers()) {
            cmbCustomer.addItem(c.getId() + " - " + c.getFullName());
        }
        
        if (cmbCustomer.getItemCount() == 0) {
            cmbCustomer.addItem("No customers yet - Add in Manage Customers");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCars = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExpectedReturnDate = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("New Car Rental Booking");

        jLabel2.setText("Available Cars");

        tblAvailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAvailableCars);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel3.setText("Select Customer");

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Rental Date (YYYY-MM-DD)");

        jLabel5.setText("Expected Return Date (YYYY-MM-DD)");

        txtExpectedReturnDate.addActionListener(this::txtExpectedReturnDateActionPerformed);

        btnCalculate.setBackground(new java.awt.Color(153, 204, 255));
        btnCalculate.setText("Calculate Total");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnBook.setBackground(new java.awt.Color(153, 204, 255));
        btnBook.setText("Book now");
        btnBook.setSize(new java.awt.Dimension(80, 25));
        btnBook.addActionListener(this::btnBookActionPerformed);

        btnRefresh.setBackground(new java.awt.Color(153, 204, 255));
        btnRefresh.setText("Refresh Available Cars");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnClose.setBackground(new java.awt.Color(153, 204, 255));
        btnClose.setText("Go Back");
        btnClose.setPreferredSize(new java.awt.Dimension(81, 25));
        btnClose.addActionListener(this::btnCloseActionPerformed);

        lblTotal.setText("Total Amount: ₺0.00");

        jLabel7.setText("Booking Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnRefresh)
                                .addGap(23, 23, 23)
                                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(btnBook)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtExpectedReturnDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotal))
                            .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpectedReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculate)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBook)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpectedReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpectedReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpectedReturnDateActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
        String rentalStr = txtRentalDate.getText().trim();
        String returnStr = txtExpectedReturnDate.getText().trim();

        if (rentalStr.isEmpty() || returnStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both Rental Date and Expected Return Date (YYYY-MM-DD)");
            lblTotal.setText("Total Amount: ₺0.00");
            return;
        }

        // Get selected car daily rate
        int row = tblAvailableCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car first!");
            return;
        }

        double dailyRate = (double) tableModel.getValueAt(row, 4);

        // Simple date difference calculation (basic version)
        // This assumes dates are in YYYY-MM-DD format
        java.time.LocalDate rentalDate = java.time.LocalDate.parse(rentalStr);
        java.time.LocalDate returnDate = java.time.LocalDate.parse(returnStr);

        long days = java.time.temporal.ChronoUnit.DAYS.between(rentalDate, returnDate);

        if (days <= 0) {
            JOptionPane.showMessageDialog(this, "Return date must be after rental date!");
            lblTotal.setText("Total Amount: ₺0.00");
            return;
        }

        double totalAmount = days * dailyRate;

        // Show the result in the label
        lblTotal.setText(String.format("Total Amount: ₺%.2f (%d days)", totalAmount, days));

        JOptionPane.showMessageDialog(this, "Calculation done!\n" + 
            days + " days × ₺" + dailyRate + " = ₺" + String.format("%.2f", totalAmount));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error in calculation.\nMake sure dates are in YYYY-MM-DD format.");
        lblTotal.setText("Total Amount: ₺0.00");
        System.out.println("Calculation error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        int row = tblAvailableCars.getSelectedRow();
        if (row == -1 || cmbCustomer.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Select car and customer!");
            return;
        }


        int confirm = JOptionPane.showConfirmDialog(this, 
            "Proceed with payment and booking?", 
            "Payment Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            int carId = (int) tableModel.getValueAt(row, 0);
            // Change car status to Rented
            for (Car c : dm.getCars()) {
                if (c.getId() == carId) {
                    c.setStatus("Rented");
                    break;
                }
            }

            JOptionPane.showMessageDialog(this, "✅ Booking & Payment Successful!\nCar is now Rented.");
            refreshAvailableCars();
            lblTotal.setText("Total Amount: ₺0.00");
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshAvailableCars();
        loadCustomersToCombo();
        JOptionPane.showMessageDialog(this, "Available cars and customers refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new DashboardForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblAvailableCars;
    private javax.swing.JTextField txtExpectedReturnDate;
    private javax.swing.JTextField txtRentalDate;
    // End of variables declaration//GEN-END:variables
}
