/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.gui;

import carrentalsystem.model.Car;
import carrentalsystem.model.Customer;
import carrentalsystem.model.Rental;
import carrentalsystem.util.FileManager;
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alianaam
 */
public class BookForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookForm.class.getName());
    private List<Car> carList = new ArrayList<>();
    private List<Customer> customerList = new ArrayList<>();
    private List<Rental> rentalList = new ArrayList<>();
    private DefaultTableModel tableModel;


    /**
     * Creates new form BookForm
     */
    public BookForm() {
        initComponents();
        loadAllData();
        setupTable();
        refreshAvailableCars();
        loadCustomersToCombo();
    }
    
    private void loadAllData() {
        // Load cars
        carList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("cars.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length == 6) {
                    carList.add(new Car(Integer.parseInt(p[0]), p[1], p[2], p[3], Double.parseDouble(p[4]), p[5]));
                }
            }
        } catch (Exception e) {}
        
        // Load customers
        customerList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("customers.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length == 5) {
                    customerList.add(new Customer(Integer.parseInt(p[0]), p[1], p[2], p[3], p[4]));
                }
            }
        } catch (Exception e) {}
        
        // Load rentals
        rentalList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("rentals.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Simple load - we'll improve later if needed
            }
        } catch (Exception e) {}
    }

    private void setupTable() {
        tableModel = new DefaultTableModel(
            new String[]{"Car ID", "Brand", "Model", "Plate", "Daily Rate"}, 0);
        tblAvailableCars.setModel(tableModel);
    }
    private void refreshAvailableCars() {
        tableModel.setRowCount(0);
        for (Car c : carList) {
            if (c.getStatus().equals("Available")) {
                tableModel.addRow(new Object[]{
                    c.getId(), c.getBrand(), c.getModel(), c.getPlateNumber(), c.getDailyRate()
                });
            }
        }
    }
    private void loadCustomersToCombo() {
        cmbCustomer.removeAllItems();
        for (Customer c : customerList) {
            cmbCustomer.addItem(c.getId() + " - " + c.getFullName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailableCars = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRentalDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExpectedReturnDate = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Car Rental Booking");

        jLabel2.setText("Available Cars");

        tblAvailableCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAvailableCars);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel3.setText("Select Customer");

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Rental Date (YYYY-MM-DD)");

        jLabel5.setText("Expected Return Date (YYYY-MM-DD)");

        txtExpectedReturnDate.addActionListener(this::txtExpectedReturnDateActionPerformed);

        btnCalculate.setText("Calculate Total");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        jLabel6.setText("Total Amount:");

        btnBook.setText("Book now");
        btnBook.addActionListener(this::btnBookActionPerformed);

        btnRefresh.setText("Refresh Available Cars");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtExpectedReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCalculate)
                                    .addComponent(jLabel6)
                                    .addComponent(btnBook)
                                    .addComponent(btnRefresh))))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRentalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExpectedReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(btnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExpectedReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpectedReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpectedReturnDateActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        try {
            String rentalStr = txtRentalDate.getText().trim();
            String returnStr = txtExpectedReturnDate.getText().trim();

            if (rentalStr.isEmpty() || returnStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter both dates (YYYY-MM-DD)");
                return;
            }

            // Simple days calculation
            // For real project you can improve this
            JOptionPane.showMessageDialog(this, "Total calculation coming in next version.\nPlease enter dates in YYYY-MM-DD format.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error in calculation");
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        int row = tblAvailableCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car from the table!");
            return;
        }
        if (cmbCustomer.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a customer!");
            return;
        }
        
         try {
            int carId = (int) tableModel.getValueAt(row, 0);
            String customerStr = cmbCustomer.getSelectedItem().toString();
            int customerId = Integer.parseInt(customerStr.split(" - ")[0]);

            String rentalDate = txtRentalDate.getText().trim();
            String expectedReturn = txtExpectedReturnDate.getText().trim();

            if (rentalDate.isEmpty() || expectedReturn.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill rental and return dates!");
                return;
            }
            
            // Update car status to Rented
            for (Car c : carList) {
                if (c.getId() == carId) {
                    c.setStatus("Rented");
                    break;
                }
            }
            // Save updated cars
            FileManager.saveCars(carList);

            JOptionPane.showMessageDialog(this, "✅ Booking Successful!\nCar ID: " + carId + "\nCustomer ID: " + customerId);

            refreshAvailableCars();
            txtRentalDate.setText("");
            txtExpectedReturnDate.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Booking failed: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadAllData();
        refreshAvailableCars();
        JOptionPane.showMessageDialog(this, "Available cars refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAvailableCars;
    private javax.swing.JTextField txtExpectedReturnDate;
    private javax.swing.JTextField txtRentalDate;
    // End of variables declaration//GEN-END:variables
}
