/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.gui;

/**
 *
 * @author alianaam
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());
    

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageCars = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        btnNewBooking = new javax.swing.JButton();
        btnViewRentals = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Car Rental System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        btnManageCars.setText("Manage Cars");
        btnManageCars.addActionListener(this::btnManageCarsActionPerformed);
        getContentPane().add(btnManageCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 62, -1, -1));

        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.addActionListener(this::btnManageCustomersActionPerformed);
        getContentPane().add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 97, -1, -1));

        btnNewBooking.setText("New Booking");
        btnNewBooking.addActionListener(this::btnNewBookingActionPerformed);
        getContentPane().add(btnNewBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, -1, -1));

        btnViewRentals.setText("View / Return Rentals");
        btnViewRentals.addActionListener(this::btnViewRentalsActionPerformed);
        getContentPane().add(btnViewRentals, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 173, -1, -1));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCarsActionPerformed
        // TODO add your handling code here:
        new ManageCarForm().setVisible(true);
    }//GEN-LAST:event_btnManageCarsActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
        new ManageCustomerForm().setVisible(true);
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnNewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookingActionPerformed
        // TODO add your handling code here:
        new BookForm().setVisible(true);

    }//GEN-LAST:event_btnNewBookingActionPerformed

    private void btnViewRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRentalsActionPerformed
        // TODO add your handling code here:
        new RentalForm().setVisible(true);

    }//GEN-LAST:event_btnViewRentalsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCars;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnNewBooking;
    private javax.swing.JButton btnViewRentals;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
