/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package carrentalsystem.gui;


/**
 *
 * @author alianaam
 */
public class ManageCarsForm extends javax.swing.JFrame {

    private List<Car> carList = new ArrayList<>();
    private int nextCarId = 1;
    private DefaultTableModel tableModel;

    public ManageCarsForm() {
        initComponents();
        loadCarsFromFile();
        setupTable();
        refreshTable();
        
        // Setup ComboBox
        cmbStatus.setModel(new DefaultComboBoxModel<>(new String[]{"Available", "Rented", "Maintenance"}));
    }
    private void setupTable() {
        tableModel = new DefaultTableModel(
            new String[]{"ID", "Brand", "Model", "Plate Number", "Daily Rate", "Status"}, 0);
        tblCars.setModel(tableModel);
    }

    private void loadCarsFromFile() {
        carList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("cars.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length == 6) {
                    Car c = new Car(Integer.parseInt(p[0]), p[1], p[2], p[3],
                            Double.parseDouble(p[4]), p[5]);
                    carList.add(c);
                    if (c.getId() >= nextCarId) nextCarId = c.getId() + 1;
                }
            }
        } catch (Exception e) {
            // First run - no file yet
        }
    }
    private void refreshTable() {
        tableModel.setRowCount(0);
        for (Car c : carList) {
            tableModel.addRow(new Object[]{
                c.getId(), c.getBrand(), c.getModel(), c.getPlateNumber(),
                c.getDailyRate(), c.getStatus()
            });
        }
    }

    private void clearFields() {
        txtBrand.setText("");
        txtModel.setText("");
        txtPlate.setText("");
        txtDailyRate.setText("");
        cmbStatus.setSelectedIndex(0);
        txtSearch.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtPlate = new javax.swing.JTextField();
        txtDailyRate = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Manage Cars");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Brand", "Model", "Plate", "Daily Rate", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblCars);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 570, 340));

        txtBrand.setText("Brand");
        txtBrand.addActionListener(this::txtBrandActionPerformed);
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtModel.setText("Model");
        txtModel.addActionListener(this::txtModelActionPerformed);
        getContentPane().add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        txtPlate.setText("Plate Number");
        txtPlate.addActionListener(this::txtPlateActionPerformed);
        getContentPane().add(txtPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        txtDailyRate.setText("Daily Rate");
        txtDailyRate.addActionListener(this::txtDailyRateActionPerformed);
        getContentPane().add(txtDailyRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatus.addActionListener(this::cmbStatusActionPerformed);
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtSearch.setText("Search");
        txtSearch.addActionListener(this::txtSearchActionPerformed);
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        btnAdd.setBackground(new java.awt.Color(102, 255, 102));
        btnAdd.setText("Add Car");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel2.setText("Brand");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setText("Model");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jLabel4.setText("Plate Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel5.setText("Daily Rate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel10.setText("Search:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            if (txtBrand.getText().trim().isEmpty() || txtPlate.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Brand and Plate Number are required!");
                return;
            }
            Car car = new Car(nextCarId++, 
                    txtBrand.getText().trim(), 
                    txtModel.getText().trim(), 
                    txtPlate.getText().trim(), 
                    Double.parseDouble(txtDailyRate.getText().trim()), 
                    cmbStatus.getSelectedItem().toString());

            carList.add(car);
            FileManager.saveCars(carList);
            refreshTable();
            clearFields();
            JOptionPane.showMessageDialog(this, "Car added successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlateActionPerformed

    private void txtDailyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDailyRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDailyRateActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String keyword = txtSearch.getText().trim().toLowerCase();
        tableModel.setRowCount(0);
        for (Car c : carList) {
            if (c.getBrand().toLowerCase().contains(keyword) || 
                c.getModel().toLowerCase().contains(keyword) || 
                c.getPlateNumber().toLowerCase().contains(keyword)) {
                tableModel.addRow(new Object[]{
                    c.getId(), c.getBrand(), c.getModel(), c.getPlateNumber(),
                    c.getDailyRate(), c.getStatus()
                });
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tblCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car from the table to update!");
            return;
        }
        try {
            int id = (int) tableModel.getValueAt(row, 0);
            Car car = carList.stream().filter(c -> c.getId() == id).findFirst().orElse(null);
            if (car != null) {
                car.setBrand(txtBrand.getText().trim());
                car.setModel(txtModel.getText().trim());
                car.setPlateNumber(txtPlate.getText().trim());
                car.setDailyRate(Double.parseDouble(txtDailyRate.getText().trim()));
                car.setStatus(cmbStatus.getSelectedItem().toString());

                FileManager.saveCars(carList);
                refreshTable();
                JOptionPane.showMessageDialog(this, "Car updated successfully!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car to delete!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this car?", 
                                                    "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int id = (int) tableModel.getValueAt(row, 0);
            carList.removeIf(c -> c.getId() == id);
            FileManager.saveCars(carList);
            refreshTable();
            clearFields();
            JOptionPane.showMessageDialog(this, "Car deleted successfully!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadCarsFromFile();
        refreshTable();
        JOptionPane.showMessageDialog(this, "Data refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed
     
    private void tblCarsMouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblCars.getSelectedRow();
        if (row != -1) {
            txtBrand.setText(tableModel.getValueAt(row, 1).toString());
            txtModel.setText(tableModel.getValueAt(row, 2).toString());
            txtPlate.setText(tableModel.getValueAt(row, 3).toString());
            txtDailyRate.setText(tableModel.getValueAt(row, 4).toString());
            cmbStatus.setSelectedItem(tableModel.getValueAt(row, 5).toString());
        }
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageCarsForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtDailyRate;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
