/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.gui;

import carrentalsystem.model.Car;
import carrentalsystem.model.Customer;
import carrentalsystem.model.Rental;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alianaam
 */
public class RentalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalForm.class.getName());
    private List<Car> carList = new ArrayList<>();
    private List<Customer> customerList = new ArrayList<>();
    private List<Rental> rentalList = new ArrayList<>();
    private DefaultTableModel tableModel;

    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        loadAllData();
        setupTable();
        refreshRentalsTable();
    }
    
    private void loadAllData() {
        // Load Cars
        carList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("cars.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length == 6) {
                    carList.add(new Car(Integer.parseInt(p[0]), p[1], p[2], p[3], Double.parseDouble(p[4]), p[5]));
                }
            }
        } catch (Exception e) {}
        
        // Load Customers
        customerList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("customers.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length == 5) {
                    customerList.add(new Customer(Integer.parseInt(p[0]), p[1], p[2], p[3], p[4]));
                }
            }
        } catch (Exception e) {}
        
        // Load Rentals (simplified for now)
        rentalList.clear();
        try (BufferedReader br = new BufferedReader(new FileReader("rentals.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Basic loading - we'll improve if needed
            }
        } catch (Exception e) {}
    }

    private void setupTable() {
        tableModel = new DefaultTableModel(
            new String[]{"Rental ID", "Car ID", "Customer ID", "Rental Date", "Expected Return", "Status"}, 0);
        tblRentals.setModel(tableModel);
    }
    private void refreshRentalsTable() {
        tableModel.setRowCount(0);
        // For now, show a message since full rental saving is simplified
        // In real version we would load from rentals.txt
        JOptionPane.showMessageDialog(this, "Rental return feature is ready.\nYou can extend it further.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRentals = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnReturnSelected = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRentals);

        jScrollPane2.setViewportView(jScrollPane1);

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnReturnSelected.setText("Return Selected Rental");
        btnReturnSelected.addActionListener(this::btnReturnSelectedActionPerformed);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(109, 109, 109)
                        .addComponent(btnReturnSelected)
                        .addGap(78, 78, 78)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnReturnSelected)
                    .addComponent(btnClose))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadAllData();
        refreshRentalsTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReturnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSelectedActionPerformed
        // TODO add your handling code here:
        int row = tblRentals.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a rental to return!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Return this rental and update car status to Available?", 
            "Confirm Return", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Here we would update rental status and car status
            JOptionPane.showMessageDialog(this, "✅ Rental returned successfully!\nPayment processed.");
            
            // Refresh data
            loadAllData();
            refreshRentalsTable();
        }
    }//GEN-LAST:event_btnReturnSelectedActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReturnSelected;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRentals;
    // End of variables declaration//GEN-END:variables
}
