/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem.gui;

import carrentalsystem.model.Car;
import carrentalsystem.model.Customer;
import carrentalsystem.model.Rental;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alianaam
 */
public class RentalForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RentalForm.class.getName());
    private final DataManager dm = DataManager.getInstance();
    private DefaultTableModel tableModel;

    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        setupTable();
        refreshRentalsTable();
        getContentPane().setBackground(new java.awt.Color(240, 248, 255)); // light blue background
        setTitle("Car Rental System");
    }
    
    private void setupTable() {
        tableModel = new DefaultTableModel(
            new String[]{"Car ID", "Brand", "Model", "Plate Number", "Daily Rate", "Status"}, 0);
        tblRentals.setModel(tableModel);
    }
    
    private void refreshRentalsTable() {
        tableModel.setRowCount(0);
        int rentedCount = 0;

        for (Car c : dm.getCars()) {
            if ("Rented".equals(c.getStatus())) {
                tableModel.addRow(new Object[]{
                    c.getId(), c.getBrand(), c.getModel(), 
                    c.getPlateNumber(), c.getDailyRate(), c.getStatus()
                });
                rentedCount++;
            }
        }

        if (rentedCount == 0) {
            JOptionPane.showMessageDialog(this, "No active rentals at the moment.");
        } else {
            System.out.println("✅ Showing " + rentedCount + " rented cars");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRentals = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnReturnSelected = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRentals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRentals);

        jScrollPane2.setViewportView(jScrollPane1);

        btnRefresh.setBackground(new java.awt.Color(153, 204, 255));
        btnRefresh.setText("Refresh List");
        btnRefresh.setPreferredSize(new java.awt.Dimension(100, 25));
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnReturnSelected.setBackground(new java.awt.Color(153, 204, 255));
        btnReturnSelected.setText("Return Selected Rental");
        btnReturnSelected.setPreferredSize(new java.awt.Dimension(164, 25));
        btnReturnSelected.addActionListener(this::btnReturnSelectedActionPerformed);

        btnClose.setBackground(new java.awt.Color(153, 204, 255));
        btnClose.setText("Go Back");
        btnClose.setPreferredSize(new java.awt.Dimension(81, 25));
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnReturnSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshRentalsTable();
        JOptionPane.showMessageDialog(this, "Rentals list refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReturnSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSelectedActionPerformed
        // TODO add your handling code here:
        int row = tblRentals.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a rental to return!");
            return;
        }

        int carId = (int) tableModel.getValueAt(row, 0);
        String carBrand = tableModel.getValueAt(row, 1).toString();
        String carModel = tableModel.getValueAt(row, 2).toString();

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Return this car?\n" + carBrand + " " + carModel + " (ID: " + carId + ")", 
            "Confirm Return", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            // Change car status back to Available
            for (Car c : dm.getCars()) {
                if (c.getId() == carId) {
                    c.setStatus("Available");
                    break;
                }
            }

            JOptionPane.showMessageDialog(this, "✅ Car returned successfully!\n" +
                    "Car: " + carBrand + " " + carModel + "\nStatus: Available");

            refreshRentalsTable();
        }
        
    }//GEN-LAST:event_btnReturnSelectedActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        new DashboardForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RentalForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReturnSelected;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRentals;
    // End of variables declaration//GEN-END:variables
}
